wandb:
  project: ghibli-gan
  data:
    artifact_name: ghibli-image-dataset
    artifact_type: dataset
    job_type: upload-dataset

scraper:
  query: Totoro character isolated
  num_images: 200
  output_dir: data

logging:
  level: INFO